import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from 'next-auth';
import Link from 'next/link';
import { authOptions } from "@/lib/auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <header className="bg-gray-800 text-white p-4 flex justify-between items-center">
          <h1 className="text-lg font-bold"> TDG Connect by KSRX</h1>
          {session ? (
            <div className="flex items-center space-x-4">
              <span>Welcome, {session.user?.name || 'User'}</span>
              <Link href="/api/auth/signout" className="bg-red-600 hover:bg-red-700 text-white px-3 py-1 rounded-md text-sm transition-colors">
                Logout
              </Link>
            </div>
          ) : (
            <Link href="/auth/login" className="text-blue-400 hover:underline">
              Login
            </Link>
          )}
        </header>
        {children}
      </body>
    </html>
  );
}
